/*!
 * Copyright 2023 - 2026 California Department of Motor Vehicles
 * Copyright 2023 - 2026 Digital Bazaar, Inc.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

import {config} from '@bedrock/core';
import expect from 'expect.js';
import {generateValidJwtVpToken} from '../utils/jwtVpTokens.js';
import {verifySubmission} from '../../lib/workflows/common/oid4vp-shared.js';

// Matches the default `aud` baked into generateValidJwtVpToken so the VP-JWT
// audience check passes when used as the authorization request `client_id`.
const aud = 'did:web:localhost:22443';
const challenge = 'test-challenge-123';

// Presentation definition whose single input descriptor constrains `$.type`
// to the credential generated by generateValidJwtVpToken (a v1
// UniversityDegreeCredential), so the final checkVcQueryMatch gate passes.
const presentationDefinition = {
  id: 'test-pd',
  input_descriptors: [{
    id: 'vc',
    constraints: {
      fields: [{
        path: ['$.type'],
        filter: {
          type: 'array',
          contains: {type: 'string', const: 'UniversityDegreeCredential'}
        }
      }]
    }
  }]
};

// Builds a Draft 18 presentation_submission whose descriptor_map roots the
// nested VC at `path`. This is what verifyDraft18Submission turns into the
// production `vcQuery`.
const makeSubmission = path => ({
  id: 'urn:uuid:sub',
  definition_id: presentationDefinition.id,
  descriptor_map: [{
    id: 'vc',
    path: '$',
    format: 'jwt_vp_json',
    path_nested: {format: 'jwt_vc_json', path}
  }]
});

const workflow = {clientId: 'test', trustedCredentialIssuers: []};

const buildExchange = () => ({
  id: 'test-exchange',
  challenge,
  variables: {
    authorizationRequest: {
      client_id: aud,
      presentation_definition: presentationDefinition
    }
  }
});

describe('OID4VP jwt_vp_json path_nested rooting', function() {
  let vpToken;
  let originalCaStore;
  let originalAuditEnable;

  before(async function() {
    ({vpToken} = await generateValidJwtVpToken({aud, challenge}));

    // Isolate path resolution behavior: the generated token has an empty x5c,
    // so drop any configured CAs to skip the x509 branch, and disable audit so
    // no DID document history write is attempted.
    originalCaStore = config.opencred.caStore;
    config.opencred.caStore = [];
    if(config.opencred.audit) {
      originalAuditEnable = config.opencred.audit.enable;
      config.opencred.audit.enable = false;
    }
  });

  after(function() {
    config.opencred.caStore = originalCaStore;
    if(config.opencred.audit) {
      config.opencred.audit.enable = originalAuditEnable;
    }
  });

  it('resolves the VC when path_nested has root $.vp',
    async function() {
      // Some wallets inject an extra `.vp` wrapper in their query.
      // unenvelopeJwtVp strips the `.vp` wrapper, so a `$.vp`-rooted path only
      // resolves via the `{vp}`-wrapped fallback in verifyJwtSubmission.
      const result = await verifySubmission({
        workflow,
        vp_token: vpToken,
        submission: makeSubmission('$.vp.verifiableCredential[0]'),
        exchange: buildExchange()
      });

      expect(result.errors).to.not.contain('VC not found in presentation');
      expect(result.verifiablePresentation).to.be.an('object');
      expect(result.verified).to.be(true);
    });

  it('resolves the VC when path_nested has root of the unwrapped VP',
    async function() {
      const result = await verifySubmission({
        workflow,
        vp_token: vpToken,
        submission: makeSubmission('$.verifiableCredential[0]'),
        exchange: buildExchange()
      });

      expect(result.errors).to.not.contain('VC not found in presentation');
      expect(result.verifiablePresentation).to.be.an('object');
      expect(result.verified).to.be(true);
    });
});
