# Copyright 2023 - 2025 California Department of Motor Vehicles
# Copyright 2023 - 2025 Digital Bazaar, Inc.
#
# SPDX-License-Identifier: BSD-3-Clause

app:
  # server:
  # baseUri: https://evil-cows-return.loca.lt
  opencred:
    caStore:
      - pem: |
          -----BEGIN CERTIFICATE-----
          <VALID CERTIFICATE>
          -----END CERTIFICATE-----
    signingKeys:
      - type: ES256
        privateKeyPem: |
          -----BEGIN PRIVATE KEY-----
          <VALID PRIVATE KEY>
          -----END PRIVATE KEY-----
        publicKeyPem: |
          -----BEGIN PUBLIC KEY-----
          <VALID PUBLIC KEY>
          -----END PUBLIC KEY-----
        purpose:
          - authorization_request
    workflows:
      - name: "Test Workflow (Native)"
        clientId: "rp1"
        clientSecret: "DeepestAndDarkest"
        type: native
        description: "Test App"
        brand:
          primaryLogo: "https://placekitten.com/200/200"
          primaryLink: "https://example.com"
          secondaryLogo: "https://placekitten.com/200/200"
          secondaryLink: "https://example2.com"
          homeLink: "https://example.com"
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
          explainerVideo:
            id: "<YOUTUBE ID>"
            provider: youtube
          backgroundImage: "https://placekitten.com/800/200"
        oidc:
          redirectUri: "http://localhost:3000"
          idTokenExpirySeconds: 3600
          claims:
            - name: "dl_number"
              path: "driversLicense.document_number"
          scopes:
            - name: "openid"
              description: "Open ID Connect"
        callback:
          url: http://localhost:9000/callback
          headersVariable: callbackHeaders
          oauth:
            issuer: http://example.com
            tokenUrl: http://example.com/token
            clientSecret: exampleClientSecret
            clientId: exampleClientId
            scope:
              - default
        verifiablePresentationRequest: >
          {
            "query": {
              "type": "QueryByExample",
              "credentialQuery": {
                "reason": "Please present your VC.",
                "example": {
                  "type": [
                    "Iso18013DriversLicenseCredential"
                  ]
                }
              }
            }
          }
      - name: "Test App"
        # An example that uses a remote VC-API exchanger to connect with a wallet
        # See Verifiable Credentials API Documentation: https://w3c-ccg.github.io/vc-api/
        clientId: "32bb6cec384b"
        clientSecret: "DeepestAndDarkest"
        type: vc-api
        description: "Test App"
        brand:
          primaryLogo: "https://placekitten.com/200/200"
          backgroundImage: "https://placekitten.com/800/300"
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
        oidc:
          redirectUri: "http://localhost:3000"
          idTokenExpirySeconds: 3600
          claims:
            - name: "email"
              path: "email"
          scopes:
            - name: "openid"
              description: "Open ID Connect"
        baseUrl: https://example.org/workflows/123
        capability: "example"
        verifiablePresentationRequest: >
          {
            "query": {
              "type": "QueryByExample",
              "credentialQuery": {
                "reason": "Please present your VC.",
                "example": {
                  "type": [
                    "VerifiableCredential"
                  ]
                }
              }
            }
          }
      - clientId: 4e3a8b7b4b7b4b7b4b7b
        # Microsoft Entra Verified Id workflow config
        # Many of these config fields map to request fields in the APIs linked below:
        #   https://learn.microsoft.com/en-us/entra/verified-id/get-started-request-api
        #   https://learn.microsoft.com/en-us/entra/verified-id/presentation-request-api
        type: microsoft-entra-verified-id
        caStore: false
        configFrom: 32bb6cec384b # clientId of another workflow to serve as default values
        trustedCredentialIssuers:
          - did:web:example.com
        apiBaseUrl: https://api.entra.microsoft.example.com/v1.0 # required (will generally be https://verifiedid.did.msidentity.com/v1.0)
        apiLoginBaseUrl: https://login.entra.microsoft.example.com # required (will generally be https://login.microsoftonline.com)
        apiClientId: "TODO" # required
        apiClientSecret: "TODO" # required
        apiTenantId: "TODO" # required
        verifierDid: "TODO" # required
        verifierName: "TODO" # required
        acceptedCredentialType: "TODO" # required
        credentialVerificationPurpose: "So that we can evaluate your permission to access the requested resource" # optional (default populated in middleware unless overridden here)
        allowRevokedCredentials: false # optional (default populated in middleware unless overridden here)
        validateLinkedDomain: false # optional (default populated in middleware unless overridden here)
      - name: "load-test"
        clientId: "load-test"
        clientSecret: "DeepestAndDarkest"
        type: native
        description: "Load Testing Profile"
        brand:
          primaryLogo: "https://imagedelivery.net/I-hc6FAYxquPgv-npvTcWQ/241cb0c9-d92c-40b7-1745-6d5e68a45d00/public"
          backgroundImage: "https://imagedelivery.net/I-hc6FAYxquPgv-npvTcWQ/f7516576-f9d3-4a15-1b9e-e95281613700/public"
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
        oidc:
          redirectUri: "http://localhost:3000"
          idTokenExpirySeconds: 3600
          claims:
            - name: "dl_number"
              path: "driversLicense.document_number"
          scopes:
            - name: "openid"
              description: "Open ID Connect"
        verifiablePresentationRequest: >
          {
            "query": {
              "type": "QueryByExample",
              "credentialQuery": {
                "reason": "Please present your VC.",
                "example": {
                  "type": [
                    "DomainLinkageCredential"
                  ]
                }
              }
            }
          }
      - name: "Permanent Resident Card Verifier"
        clientId: "prc-verifier"
        clientSecret: "DeepestAndDarkest"
        type: native
        description: "Permanent Resident Card Verification Service"
        brand:
          primaryLogo: "https://placekitten.com/200/200"
          backgroundImage: "https://placekitten.com/800/300"
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
        oidc:
          redirectUri: "http://localhost:3000"
          idTokenExpirySeconds: 3600
          scopes:
            - name: "openid"
              description: "Open ID Connect"
        query:
          - type:
              - PermanentResidentCard
            context:
              - "https://www.w3.org/2018/credentials/v1"
              - "https://w3id.org/citizenship/v1"
              - "https://w3id.org/security/suites/ed25519-2020/v1"
            format:
              - ldp_vc
      - name: "Driver's License (Preset)"
        clientId: "basic-dl"
        clientSecret: "basic-dl-secret"
        type: preset
        preset: Iso18013DriversLicenseCredential:2025
        trustedCredentialIssuers:
          - did:web:example.com
        public: true
      - name: "Mobile Driver's License (DC API)"
        clientId: "native-mdl"
        clientSecret: "native-mdl-secret"
        type: native
        dcApiNamespaceQuery:
          org.iso.18013.5.1:
            - family_name
            - given_name
            - document_number
        dcApiEnabled: true
        public: true
      - name: "Driver's License Query"
        clientId: "query-dl"
        clientSecret: "query-dl-secret"
        type: native
        query:
          - type:
              - Iso18013DriversLicenseCredential
            context:
              - "https://www.w3.org/2018/credentials/v1"
              - "https://w3id.org/vdl/v1"
              - "https://w3id.org/vdl/aamva/v1"
            format:
              - jwt_vc_json
        public: true
    options:
      exchangeProtocols:
        - chapi
        - openid4vp
      recordExpiresDurationMs: 86400000
    defaultBrand:
      cta: "#0B669D"
      primary: "#045199"
      header: "#0979c4"
    audit:
      enable: true
      types:
        - preset: Iso18013DriversLicenseCredential:2025
        - name: Custom Audit Profile
          fields:
            - type: text
              id: given_name
              name: First Name
              path: "$.credentialSubject.given_name"
              required: true
            - type: text
              id: family_name
              name: Last Name
              path: "$.credentialSubject.family_name"
              required: false
            - type: date
              id: birth_date
              name: Date of Birth
              path: "$.credentialSubject.birth_date"
              required: true
            - type: number
              id: height
              name: Height (cm)
              path: "$.credentialSubject.height"
              required: false
            - type: dropdown
              id: sex
              name: Sex
              path: "$.credentialSubject.sex"
              required: false
              options:
                "Male": 1
                "Female": 2
            - type: dropdown
              id: senior_citizen
              name: Are you a senior citizen?
              path: "$.credentialSubject.senior_citizen"
              required: true
              options:
                "Yes": 1
                "No": null
              default: "No"
    reCaptcha:
      enable: true
      version: 2
      siteKey: 6LcNDSjdAAAAAAAAIe2uy0gavf0reiuhfer12345
      secretKey: 6LcNDSjdAAAAAAAAIe3uy1gavf1reiuhfer67890
      pages:
        - audit
    defaultLanguage: en
    translations:
      en:
        qrTitle: Login with your Wallet app
        qrPageExplain: Scan the following QR Code using the Wallet app on your phone.
        qrPageExplainHelp: (<a href="https://youtube.com">How do I do it?</a>)
        qrFooter: "Note: Already on your phone with the Wallet app? Open the Wallet app, then come back and tap on the QR code above."
        qrFooterHelp: Difficulty using the Wallet app to login? revert to using password <a href="#">here</a>
        qrDisclaimer: If you don't have a Wallet app download it from the app store.
        qrExplainerText: (How do I do it?)
        chapiPageAnotherWay: "Looking for a QR code to scan with your wallet app instead?"
        loginCta: "Login with your credential wallet"
        loginExplain: "To login with your credential wallet, you will need to have the credential wallet app <with configurable URL to app stores> installed"
        appInstallExplain: "If you don't have a credential wallet yet, you can get one by downloading the credential wallet app <with configurable URL to app stores>"
        appCta: "Open wallet app"
        copyright: "Powered by OpenCred"
        pageTitle: "Login"
        home: "Home"
        verificationSuccess: "Success! Your credential has been shared."
        exchangeActiveGoBack: Back
        exchangeActiveExpiryMessage: "Please complete within the allotted time:"
        exchangeErrorTitle: Exchange failed
        exchangeErrorSubtitle: "Error details:"
        exchangeResetTitle: Please try again.
        exchangeReset: Retry exchange
