/*!
 * Copyright 2023 - 2026 California Department of Motor Vehicles
 * Copyright 2023 - 2026 Digital Bazaar, Inc.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

import {
  generateCertificateForKey,
  generateP256SigningKey
} from './generatePrime256v1Key.js';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONFIGS_DIR = path.join(__dirname, '..', 'configs');
const COMBINED_PATH = path.join(CONFIGS_DIR, 'combined.yaml');
const GENERATED_PATH = path.join(CONFIGS_DIR, 'combined.generated.yaml');

function toYamlMultiline(pem, indent) {
  return pem.trim().split('\n').map(line => indent + line).join('\n');
}

function buildConfigYaml({
  domain, baseUri, privateKey, publicKey, certificatePem
}) {
  const keyId = crypto.createHash('sha256').update(publicKey).digest('hex');
  const pemIndent = '          ';

  return `# OpenCred Configuration File
#
# Generated by: npm run generate:config -- --domain=${domain}

app:
  server:
    baseUri: "${baseUri}"
  mongodb:
    url: "mongodb://127.0.0.1:27017/OpenCred"
  opencred:
    caStore:
      - pem: |
${toYamlMultiline(certificatePem, pemIndent)}
    signingKeys:
      - type: ES256
        id: ${keyId}
        privateKeyPem: |
${toYamlMultiline(privateKey, pemIndent)}
        publicKeyPem: |
${toYamlMultiline(publicKey, pemIndent)}
        certificatePem: |
${toYamlMultiline(certificatePem, pemIndent)}
        purpose:
          - authorization_request
    workflows:
      - name: DL VC (Preset)
        description: Driver's license VC with trusted issuer validation.
        clientId: basic-dl
        clientSecret: basic-dl-secret
        type: preset
        preset: Iso18013DriversLicenseCredential:2025
        trustedCredentialIssuers:
          - did:web:${domain}
        public: true
      - name: mDL (mDoc query)
        description: Workflow requesting mSO mdoc format. DC API.
        clientId: native-mdl
        clientSecret: native-mdl-secret
        type: native
        query:
          - fields:
              org.iso.18013.5.1:
                - family_name
                - given_name
                - document_number
            format:
              - mso_mdoc
        dcApiEnabled: true
        public: true
      - name: mDL (SpruceID)
        description: dcApiNamespaceQuery for driver's license fields. DC API.
        clientId: spruceid-dl
        clientSecret: spruceid-dl-secret
        type: native
        dcApiNamespaceQuery:
          org.iso.18013.5.1:
            - family_name
            - given_name
            - document_number
        dcApiEnabled: true
        public: true
      - name: mDL/VC DL (Hybrid)
        description: Either mSO mDoc or VC JWT JSON formats. DC API fallback.
        clientId: query-mdl-hybrid
        clientSecret: query-mdl-secret
        type: native
        query:
          - type:
              - Iso18013DriversLicenseCredential
            context:
              - "https://www.w3.org/2018/credentials/v1"
              - "https://w3id.org/vdl/v1"
              - "https://w3id.org/vdl/aamva/v1"
            format:
              - jwt_vc_json
          - fields:
              org.iso.18013.5.1:
                - family_name
                - given_name
                - document_number
            format:
              - mso_mdoc
        dcApiEnabled: true
        public: true
      - name: Open Badge (LDP VC query)
        description: Open Badges represent learning or work based achievements.
        clientId: open-badge-query
        clientSecret: open-badge-query-secret
        type: native
        query:
          - type:
              - OpenBadgeCredential
            format:
              - ldp_vc
        public: true
        wallets:
          - lcw
          - vcalm-interaction
    options:
      exchangeProtocols:
        - openid4vp
      recordExpiresDurationMs: 86400000
      exchangeTtlSeconds: 900
      includeQRByDefault: false
      OID4VPdefault: "OID4VP-1.0"
      workflowListingEnabled: false
      debug: false
      wallets:
        - cadmv-wallet
        - lcw
        - vcalm-interaction
    defaultBrand:
      cta: "#0B669D"
      primary: "#045199"
      header: "#0979c4"
    audit:
      enable: true
      types:
        - preset: Iso18013DriversLicenseCredential:2025
    defaultLanguage: en
`;
}

function parseArgs(argv) {
  let domain = null;
  for(const arg of argv) {
    if(arg.startsWith('--domain=')) {
      domain = arg.slice('--domain='.length);
      break;
    }
  }
  return {domain};
}

async function main() {
  const {domain} = parseArgs(process.argv.slice(2));

  if(!domain) {
    console.error(
      'Usage: npm run generate:config -- --domain=<domain>\n\n' +
      '  --domain  Domain for server baseUri and certificate SAN ' +
      '(e.g. opencred.example.com)'
    );
    process.exit(1);
  }

  const baseUri = `https://${domain}`;

  console.error('Generating keys and certificate...');
  const {privateKey, publicKey} = await generateP256SigningKey();

  let certificatePem;
  try {
    certificatePem = await generateCertificateForKey(privateKey, domain);
  } catch(err) {
    console.error('Failed to generate certificate:', err.message);
    process.exit(1);
  }

  const yaml = buildConfigYaml({
    domain,
    baseUri,
    privateKey,
    publicKey,
    certificatePem
  });

  const outputPath = fs.existsSync(COMBINED_PATH) ?
    GENERATED_PATH :
    COMBINED_PATH;

  if(outputPath === GENERATED_PATH) {
    console.error(
      `Warning: ${COMBINED_PATH} already exists. ` +
      `Writing to ${GENERATED_PATH} instead.`
    );
  }

  fs.mkdirSync(CONFIGS_DIR, {recursive: true});
  fs.writeFileSync(outputPath, yaml, 'utf8');

  console.error(`Config written to: ${outputPath}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
